save_cache: &save_cache
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.*
    - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
    - rm -f  $HOME/.gradle/caches/journal-1/journal-1.lock
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.konan/dependencies/

matrix:
  include:
    - os: linux
      language: java
      jdk: openjdk8
      install: true
      script:
        - ./gradlew check --no-daemon
      <<: *save_cache
    - os: osx
      language: java
      install: true
      script:
        - ./gradlew macosX64Test --no-daemon
      <<: *save_cache
    - os: windows
      language: shell
      before_install:
        - choco install -y jdk8 -params 'installdir=c:\\java8'
        - export JAVA_HOME='c:\\java8'
      install: true
      script:
        - ./gradlew.bat mingwX64Test --no-daemon
