references:
  cache: &cache
    before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $HOME/.gradle/caches/jars-3/
        - $HOME/.gradle/caches/modules-2/
        - $HOME/.gradle/wrapper/
        - $HOME/.konan/dependencies/
  linux: &linux
    os: linux
    dist: xenial
    language: java
    jdk: openjdk11
    <<: *cache
  osx: &osx
    os: osx
    osx_image: xcode10.1
    language: java
    jdk: openjdk11
    <<: *cache
  wine: &wine
    os: linux
    dist: xenial
    env:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - JAVA_HOME=c:\jdk-11.0.1
      - DRIVE_C=$HOME/.wine/drive_c
      - JDK_DIR=$DRIVE_C/jdk-11.0.1
      - USER_DIR=$DRIVE_C/users/$USER
    before_install:
      - sudo dpkg --add-architecture i386
      - curl https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
      - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
      - sudo apt-get update -q
      - sudo apt-get install -qy winehq-stable
      - wineboot
      - |
        if [ ! -e $JDK_DIR/release ]; then
          curl -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip
          unzip openjdk-11.0.1_windows-x64_bin.zip -d $DRIVE_C
        fi
    before_cache:
      - rm -f $USER_DIR/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $JDK_DIR
        - $USER_DIR/.gradle/caches/jars-3/
        - $USER_DIR/.gradle/caches/modules-2/
        - $USER_DIR/.gradle/wrapper/
        - $USER_DIR/.konan/dependencies/
  deploy: &deploy
    provider: script
    skip_cleanup: true

stages:
  - test
  - name: deploy
    if: branch = master AND type = push AND tag IS present

jobs:
  include:
    - stage: test
      <<: *linux
      install: true
      script: ./gradlew check
    - <<: *osx
      install: true
      script: ./gradlew macosX64Test
    - <<: *wine
      install: true
      script: wine cmd /c gradlew mingwX64Test
    - stage: deploy
      <<: *linux
      install: true
      script: true
      deploy:
        <<: *deploy
        script: ./gradlew publish
    - <<: *osx
      install: true
      script: true
      deploy:
        <<: *deploy
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - <<: *wine
      install: true
      script: true
      deploy:
        <<: *deploy
        script: wine cmd /c gradlew publishMingwX64PublicationToMavenRepository
