references:
  deploy_settings: &deploy_settings
    on:
      tags: true
    skip_cleanup: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.*
  - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f  $HOME/.gradle/caches/journal-1/journal-1.lock
  - rm -f  $HOME/.gradle/caches/*/fileContent/fileContent.lock
  - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache/

matrix:
  include:
    - os: linux
      language: java
      jdk: oraclejdk11
      install: true
      script: ./gradlew check
      deploy:
        provider: script
        <<: *deploy_settings
        script: ./gradlew publish
    - os: osx
      osx_image: xcode10.1
      language: java
      install: true
      script: ./gradlew macosX64Test
      deploy:
        provider: script
        <<: *deploy_settings
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - os: windows
      language: shell
      env:
        - JAVA_HOME=c:\\java11
      before_install:
        - choco install -y jdk11 -params 'installdir=c:\\java11'
      install: true
      script: ./gradlew.bat mingwX64Test --no-daemon
      deploy:
        provider: script
        <<: *deploy_settings
        script: ./gradlew.bat publishMingwX64PublicationToMavenRepository --no-daemon
