references:
  cache: &cache
    before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $HOME/.gradle/caches/jars-3/
        - $HOME/.gradle/caches/modules-2/
        - $HOME/.gradle/wrapper/
        - $HOME/.konan/dependencies/
  deploy: &deploy
    on:
      tags: true
    skip_cleanup: true

matrix:
  include:
    - os: linux
      language: java
      jdk: oraclejdk11
      install: true
      script: ./gradlew check
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publish
    - os: osx
      osx_image: xcode10.1
      language: java
      install: true
      script: ./gradlew macosX64Test
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - os: linux
      env:
        - JAVA_HOME=c:\\jdk-11.0.1
      before_install:
        - sudo apt update
        - sudo apt install -y wine64
        - curl -L -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip
        - mkdir -p $HOME/.wine/drive_c
        - unzip openjdk-11.0.1_windows-x64_bin.zip -d $HOME/.wine/drive_c
      install: true
      script: wine cmd /C ./gradlew.bat mingwX64Test
      deploy:
        provider: script
        <<: *deploy
        script: wine cmd /C ./gradlew.bat publishMingwX64PublicationToMavenRepository
