matrix:
  include:
    - os: linux
      language: java
      jdk: oraclejdk8
      script:
        - ./gradlew check --no-daemon
    - os: windows
      language: shell
      script:
        - ./gradlew.bat mingwX64Test --no-daemon
    - os: osx
      language: java
      jdk: oraclejdk8
      script:
        - ./gradlew check -x jsTest -x jvmTest --no-daemon
