references:
  cache: &cache
    before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $HOME/.gradle/caches/jars-3/
        - $HOME/.gradle/caches/modules-2/
        - $HOME/.gradle/wrapper/
        - $HOME/.konan/dependencies/
  deploy: &deploy
    on:
      tags: true
    skip_cleanup: true
    

language: java
jdk: oraclejdk11

matrix:
  include:
    - os: linux
      install: true
      script: ./gradlew check
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publish
    - os: osx
      osx_image: xcode10.1
      install: true
      script: ./gradlew macosX64Test
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - os: linux
      before_install:
        - sudo dpkg --add-architecture i386
        - wget -nc https://dl.winehq.org/wine-builds/Release.key
        - sudo apt-key add Release.key
        - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
        - sudo apt-get update
        - sudo apt-get install -y --install-recommends winehq-stable
        - curl -L -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip
        - wineboot
        - unzip openjdk-11.0.1_windows-x64_bin.zip -d $HOME/.wine/drive_c
        - export JAVA_HOME=c:\\jdk-11.0.1
      install: true
      script: wine cmd /C ./gradlew.bat mingwX64Test
      deploy:
        provider: script
        <<: *deploy
        script: wine cmd /C ./gradlew.bat publishMingwX64PublicationToMavenRepository
