references:
  cache: &cache
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.konan/dependencies/
  deploy: &deploy
    on:
      tags: true
    skip_cleanup: true

before_cache:
  - find $HOME/.gradle/caches/ -type f -name '*.bin' -exec rm -f {} \;
  - find $HOME/.gradle/caches/ -type f -name '*.lock' -exec rm -f {} \;
  - find $HOME/.gradle/caches/ -type f -name '*.properties' -exec rm -f {} \;

matrix:
  include:
    - os: linux
      language: java
      jdk: oraclejdk11
      install: true
      script: ./gradlew check
      cache: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publish
    - os: osx
      osx_image: xcode10.1
      language: java
      install: true
      script: ./gradlew macosX64Test
      cache: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - os: windows
      language: shell
      env:
        - JAVA_HOME=c:\\java11
      before_install:
        - choco install -y jdk11 -params 'installdir=c:\\java11'
      install: true
      script: ./gradlew.bat mingwX64Test --no-daemon
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew.bat publishMingwX64PublicationToMavenRepository --no-daemon
