references:
  cache: &cache
    before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $HOME/.gradle/caches/jars-3/
        - $HOME/.gradle/caches/modules-2/
        - $HOME/.gradle/wrapper/
        - $HOME/.konan/dependencies/
  deploy: &deploy
    on:
      tags: true
    skip_cleanup: true
    

language: java
jdk: openjdk11
install: true

matrix:
  include:
    - os: linux
      dist: xenial
      script: ./gradlew check
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publish
    - os: osx
      osx_image: xcode10.1
      script: ./gradlew macosX64Test
      <<: *cache
      deploy:
        provider: script
        <<: *deploy
        script: ./gradlew publishMacosX64PublicationToMavenRepository
                          publishIosArm32PublicationToMavenRepository
                          publishIosArm64PublicationToMavenRepository
                          publishIosX64PublicationToMavenRepository
    - os: linux
      dist: xenial
      env:
        - GRADLE_OPTS=-Dorg.gradle.daemon=false
        - JAVA_HOME=c:\jdk-11.0.1
      before_install:
        - sudo dpkg --add-architecture i386
        - wget -q https://dl.winehq.org/wine-builds/Release.key
        - sudo apt-key add Release.key
        - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
        - sudo apt-get update -q
        - sudo apt-get install -qy winehq-stable
        - wineboot
        - if [ ! -d $HOME/.wine/drive_c/jdk-11.0.1/ ]; then
            wget -q https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip;
            unzip openjdk-11.0.1_windows-x64_bin.zip -d $HOME/.wine/drive_c;
          fi
      script: wine cmd /c gradlew.bat mingwX64Test
      before_cache:
        - rm -f $HOME/.wine/drive_c/users/$USER/.gradle/caches/modules-2/modules-2.lock
      cache:
        directories:
          - $HOME/.wine/drive_c/jdk-11.0.1/
          - $HOME/.wine/drive_c/users/$USER/.gradle/caches/jars-3/
          - $HOME/.wine/drive_c/users/$USER/.gradle/caches/modules-2/
          - $HOME/.wine/drive_c/users/$USER/.gradle/wrapper/
          - $HOME/.wine/drive_c/users/$USER/.konan/dependencies/
      deploy:
        provider: script
        <<: *deploy
        script: wine cmd /c gradlew.bat publishMingwX64PublicationToMavenRepository
