references:
  cache: &cache
    before_cache:
      - rm -f $USER_DIR/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $USER_DIR/.gradle/caches/jars-3/
        - $USER_DIR/.gradle/caches/modules-2/
        - $USER_DIR/.gradle/wrapper/
        - $USER_DIR/.konan/dependencies/
  linux: &linux
    os: linux
    dist: xenial
    language: java
    jdk: openjdk11
    env:
      - USER_DIR=$HOME
    <<: *cache
  osx: &osx
    os: osx
    osx_image: xcode10.1
    language: java
    jdk: openjdk11
    env:
      - USER_DIR=$HOME
    <<: *cache
  wine: &wine
    os: linux
    dist: xenial
    env:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - JAVA_HOME=c:\jdk-11.0.1
      - DRIVE_C=$HOME/.wine/drive_c
      - USER_DIR=$DRIVE_C/users/$USER
    <<: *cache
    before_install:
      - sudo dpkg --add-architecture i386
      - curl https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
      - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
      - sudo apt-get update -q
      - sudo apt-get install -qy winehq-stable
      - wineboot
      - |
        if [ ! -e $DRIVE_C/jdk-11.0.1/release ]; then
          curl -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip
          unzip openjdk-11.0.1_windows-x64_bin.zip -d $DRIVE_C
        fi

stages:
  - test
  - name: deploy
    if: branch = master AND type = push AND tag IS present

install: true

jobs:
  include:
    - stage: test
      <<: *linux
      script: ./gradlew check
    - <<: *osx
      script: ./gradlew macosX64Test
    - <<: *wine
      script: wine cmd /c gradlew mingwX64Test
    - stage: deploy
      <<: *linux
      script: ./gradlew publish
    - <<: *osx
      script: ./gradlew publishMacosX64PublicationToMavenRepository
                        publishIosArm32PublicationToMavenRepository
                        publishIosArm64PublicationToMavenRepository
                        publishIosX64PublicationToMavenRepository
    - <<: *wine
      script: wine cmd /c gradlew publishMingwX64PublicationToMavenRepository
