version: 2

references:
  cache_key: &cache_key
    v1-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Run Lint and Tests
          command: ./gradlew ktlint check
      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan/dependencies
      - store_artifacts:
          path: btkt/build/reports
      - store_test_results:
          path: btkt/build/test-results
