version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v2-{{ checksum "build.gradle" }}-
            - v2-
      - run:
          name: Run Tests
          command: ./gradlew check
      - save_cache:
          key: v2-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan/cache
      - store_artifacts:
          path: btkt/build/reports
      - store_test_results:
          path: btkt/build/test-results
